# Do not use tabs in configuration files
# This will either lead to parsing errors, or Jekyll will revert to the default settings. Use spaces instead.
source: .
destination: _site
url: http://shadygrove.github.io/intothemountain

# Serving
detach:  false
port:    4000
host:    localhost
baseurl: "/intothemountain" # does not include hostname
basepath: "/intothemountain/"
imagespath: "assets/images/"
gallerypath: "assets/gallery/"
csspath: "assets/css/"

sass:
  sass_dir: _sass
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "main"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "main"